#!/usr/bin/with-contenv bash

apk update && apk add wget
wget https://apk.signalsciences.net/sigsci_apk.pub ; mv sigsci_apk.pub /etc/apk/keys
echo https://apk.signalsciences.net/3.12/main | tee -a /etc/apk/repositories && apk update