#!/usr/bin/with-contenv bash



if [ ! -f /usr/sbin/sigsci-agent ]; then
    echo "Installing SigSci Nginx Module and Agent"
    # echo "@nginx https://nginx.org/packages/mainline/alpine/v3.14/main" | tee -a /etc/apk/repositories >/dev/null

    # wget -O /tmp/nginx_signing.rsa.pub https://nginx.org/keys/nginx_signing.rsa.pub ; mv /tmp/nginx_signing.rsa.pub /etc/apk/keys

    # mkdir -p /tmp/etc && cp -r /etc/nginx /tmp/etc/nginx

    apk update && apk add wget # nginx@nginx

    wget https://apk.signalsciences.net/sigsci_apk.pub ; mv sigsci_apk.pub /etc/apk/keys
    echo https://apk.signalsciences.net/3.14/main | tee -a /etc/apk/repositories && apk update

    openssl rsa -pubin -in /etc/apk/keys/sigsci_apk.pub -text -noout

    # echo "restoring nginx config" && \
    #   rm -rf /etc/nginx && \
    #   cp -r /tmp/etc/nginx /etc/nginx && \
    #   mkdir -p /var/cache/nginx/client_temp && \
    #   rm -rf /tmp/etc/nginx

    apk add sigsci-agent nginx-module-sigsci-nxo-$(nginx -v |& sed 's/nginx version: nginx\///') || true
fi

